# SIDAS502: Math Methods for Data Science 


# School of Information, University of Michigan


## Week1: Vectors and Matrices Computation/Basic image processing 

### Version 1.1

This assignment will let you perform basic algebra operations using vectors and matrices in Python.  
You will use vector and matrix computation using numpy and image processing with openCV.  Please read the directions carefully to avoid submissions that are marked incorrect due to formatting mistakes. 


You can submit the assignment as many times as you like.  



Please enter your name: Ilana Multak

In [125]:
import numpy as np

## Part 1: Vector  Computation

<strong>1.1</strong> \[1 pt\] Write a function called <strong>computation</strong> that takes three variables, $a$, $v1$, and $v2$ which are an integer, and two vectors (each of which is represented as a list) and returns a dictionary that has six keys: 
* <strong>addition</strong> the sum of $v1$ and $v2$, this should be a numpy array, 
* <strong>subtraction</strong> the difference of subtracting $v2$ from $v1$, this should be a numpy array, 
* <strong>scale</strong> the scalling $v1$ by $a$, this should be a numpy array, 
* <strong>dot</strong> the dot product of $v1$ and $v2$, this should be a float, 
* <strong>length</strong> the norm of $v1$, this should be a float, and 
* <strong>cross</strong> the cross product of $v1$ and $v2$, this should be a numpy array.

Hint: Make sure that you are doing subtraction the correct way.

In [126]:
import pandas as pd
import numpy as np
from scipy.ndimage import zoom
import unittest

In [127]:
def computation(a,v1,v2):
    vector_1 = np.array(v1)
    vector_2 = np.array(v2)
    variables = {"addition": vector_1 + vector_2,
    "subtraction": vector_1 - vector_2,
    "scale": vector_1 * a,
    "dot": (vector_1 * vector_2).sum(),
    "length": np.sqrt((vector_1 * vector_1).sum()),
    "cross": np.cross(vector_1, vector_2)}
    return variables
    # YOUR CODE HERE
    #raise NotImplementedError()

In [128]:
#hidden tests for problem 1.1 are within this cell

Below is the example of computation applied to $a=1$, $v1=(1,6)$ and $v2=(8,-3)$. Run the code, play around the numbers, and check out the results.

In [129]:
v1=[1,6]
v2=[8,-3]
result = computation(1,v1,v2)
print(result)

{'addition': array([9, 3]), 'subtraction': array([-7,  9]), 'scale': array([1, 6]), 'dot': -10, 'length': 6.082762530298219, 'cross': array(-51)}


<strong>1.2</strong> \[1 pt\] What is the dimension of $v3 = (5, 4)$? Please store the dimension of $v3$ into variable <strong>v3_dimen</strong> using numpy.

For grading purposes, `v3_dimen` should be type `tuple`.  Look up and use the appropriate numpy command.  

In [130]:
v3 = np.array([5, 4])

v3_dimen=v3.shape
v3_dimen
# YOUR CODE HERE
#raise NotImplementedError()

(2,)

In [131]:
assert type(v3_dimen) == tuple, "Problem 1.2, testing v3_dimen, value stored in variable does not match the expected type. Expecting Tuple."

<strong>1.3</strong> \[1 pt\]  Let $v4 = \left(\begin{array}{c} 4 \\ 1 \end{array}\right)$.  Let $A = \left(\begin{array}{cc} 2 & 1 \\ 5 & 2 \end{array}\right)$.  

What are the dimensions of $v4$, $A$, $A \cdot v3$, and $A \cdot v4$ as computed by numpy? 

Please store the answers into the variables <strong>v4_dimen</strong>,  <strong>A_dimen</strong>,  <strong>Av3_dimen</strong>, and  <strong>Av4_dimen</strong>.  For grading purposes, all answers should be type `tuple`.

In [234]:
v4 = np.array([[4],[1]])
v4_dimen = v4.shape
v4_dimen

(2, 1)

In [228]:
assert type(v4_dimen) == tuple,  "Problem 1.3, testing v4_dimen, value stored in variable does not match the expected type. Expecting Tuple."

In [229]:
A = np.array([[2, 1], [5, 2]])
A_dimen = A.shape
A_dimen

(2, 2)

In [230]:
assert type(A_dimen) == tuple,  "Problem 1.3, testing A_dimen, value stored in variable does not match the expected type. Expecting Tuple."

In [252]:
#v3 = np.array([5, 4])
#A = np.array([[2, 1], [5, 2]])
Av3_dimen = np.array([[[2, 1], [5, 2]], [5,4]])
Av3_dimen= Av3_dimen.shape
Av3_dimen

(2, 2)

In [232]:
assert type(Av3_dimen) == tuple,  "Problem 1.3, testing Av3_dimen, value stored in variable does not match the expected type. Expecting Tuple."

In [233]:
#Av4_dimen=np.array([1,  2,  3, 4, 5])
#v4 = np.array([[4],[1]])
#A = np.array([[2, 1], [5, 2]])

Av4_dimen=np.array([[[2, 1], [5, 2]], [[4],[1]]])
Av4_dimen= Av4_dimen.shape
Av4_dimen

# YOUR CODE HERE
#raise NotImplementedError()

(2, 2)

In [196]:
assert type(Av4_dimen) == tuple,  "Problem 1.3, testing Av4_dimen, value stored in variable does not match the expected type. Expecting Tuple."

In [197]:
assert type(v4_dimen) == tuple,  "Problem 1.3, testing v4_dimen, value stored in variable does not match the expected type. Expecting Tuple."
assert type(A_dimen) == tuple,  "Problem 1.3, testing A_dimen, value stored in variable does not match the expected type. Expecting Tuple."
assert type(Av3_dimen) == tuple,  "Problem 1.3, testing Av3_dimen, value stored in variable does not match the expected type. Expecting Tuple."
assert type(Av4_dimen) == tuple,  "Problem 1.3, testing Av4_dimen, value stored in variable does not match the expected type. Expecting Tuple."


<strong>1.4</strong> \[1 pt\] Add the following two vectors by hand.  $v_1 = (5 * a, 4)$ and $v_2 = (3*b, 7)$.  

Store the results as strings in a python list called <strong>added</strong> (e.g. the vector $(5 * a, 4)$ would be ["5 * a", "4"].  Make sure that each entry in the list is a valid pyton expression.  So "5 * a" is correct, but "5 a" is not because "5 a" will not be properly evaluated by python.

In [141]:
added=["(5 * a) + (3 * b)", "11"]
added
# YOUR CODE HERE
#raise NotImplementedError()


['(5 * a) + (3 * b)', '11']

In [142]:
assert type(added) == list,  "Problem 1.4, testing added, type of value stored in variable does not match the expected type. Expecting list."

## Part 2: Matrix Computation 

<strong>2.1</strong> \[1 pt\] Write a function called <strong>Matrices</strong> that takes A matrix and B matrix, and then returns a dictionary that has four keys:
* <strong>sum</strong> (sum of $A$ and $B$), 
* <strong>difference</strong> (subtract $B$ from $A$), 
* <strong>product</strong> (product of $A$ and $B$),  
* <strong>elementwise</strong> (the elementwise product of $A$ and $B$).    

Inputs will be represented as numpy arrays and outputs should also be numpy arrays.

Hint: again, make sure you are doing subtraction the correct way.

In [143]:
def Matrices(A,B):
    return {"sum": np.add(A,B),
           "difference": np.subtract(A,B),
           "product": np.dot(A,B),
           "elementwise": np.multiply(A,B)}

Matrices(([-2,6,8],[5,-2,8],[2,1,4]), ([10,-4,6],[1,8,-3],[8,-2,4]))
    # YOUR CODE HERE
    #raise NotImplementedError()

{'sum': array([[ 8,  2, 14],
        [ 6,  6,  5],
        [10, -1,  8]]),
 'difference': array([[-12,  10,   2],
        [  4, -10,  11],
        [ -6,   3,   0]]),
 'product': array([[ 50,  40,   2],
        [112, -52,  68],
        [ 53,  -8,  25]]),
 'elementwise': array([[-20, -24,  48],
        [  5, -16, -24],
        [ 16,  -2,  16]])}

In [144]:
#hidden tests for problem 2.1 are within this cell

<strong>2.2</strong> \[1 pt\] Assume $A= \left(\begin{matrix} -2 & 6 & 8 \\ 5 & -2 & 8 \\ 2 & 1 &  4 \end{matrix} \right) $  and $B= \left(\begin{matrix} 10 & -4 & 6 \\ 1 & 8 & -3 \\ 8 & -2 &  4 \end{matrix} \right)$. What are the addition, subtraction, multiplication, and elementwise product of A matrix and B matrix? Please store your answers into a variable <strong>ANS22</strong> formatted as a dictionary as in problem 2.1.  (Use the function from 2.1) 


In [145]:
ANS22 = Matrices(([-2,6,8],[5,-2,8],[2,1,4]), ([10,-4,6],[1,8,-3],[8,-2,4]))
ANS22

{'sum': array([[ 8,  2, 14],
        [ 6,  6,  5],
        [10, -1,  8]]),
 'difference': array([[-12,  10,   2],
        [  4, -10,  11],
        [ -6,   3,   0]]),
 'product': array([[ 50,  40,   2],
        [112, -52,  68],
        [ 53,  -8,  25]]),
 'elementwise': array([[-20, -24,  48],
        [  5, -16, -24],
        [ 16,  -2,  16]])}

In [146]:
assert type(ANS22) == type({}), "Problem 2.2, testing ANS22, type of value stored in variable does not match the expected type. Expecting Dictionary."

<strong>2.3</strong> \[1 pt\] What is the transpose of C? Please store the transpose of C into a variable <strong>C_trans</strong>. 

For grading purposes, `C_trans` should be a numpy array.

In [147]:
C = np.array([[1, 1, 2], [3, 5, 8]])

C_trans=C.transpose()
C_trans
# YOUR CODE HERE
#raise NotImplementedError()

array([[1, 3],
       [1, 5],
       [2, 8]])

In [148]:
assert type(C_trans) == np.ndarray, "Problem 2.3, testing C_trans, type of value stored in variable does not match the expected type. Expecting np.ndarray"

<strong>2.4</strong> \[1 pt\] What is (CD)<sup>T</sup>? Please store the value into <strong>CD_trans.</strong>

For grading purposes, `CD_trans` should be type `numpy.array`.

In [149]:
D = np.array([[13], [21], [34]])
CD = np.dot(C,D)

CD_trans= CD.transpose()
CD_trans
# YOUR CODE HERE
#raise NotImplementedError()

array([[102, 416]])

In [150]:
#hidden tests for problem 2.4 are within this cell
assert type(CD_trans) == np.ndarray, "Problem 2.4, testing CD_trans, type of value stored in variable does not match the expected type. Expecting np.ndarray"

<strong>2.5</strong> \[1 pt\] What is the inverse matrix of E? Please store it into a variable <strong>E_inv</strong>.              

For grading purposes, `E_inv` should be type `numpy.matrix`

In [151]:
from numpy.linalg import inv
E = np.array([[1, 1, 2], [3, 5, 8], [13, 21, 50]])

E_inv=inv(np.matrix(E))
E_inv
#raise NotImplementedError()

matrix([[ 2.5625, -0.25  , -0.0625],
        [-1.4375,  0.75  , -0.0625],
        [-0.0625, -0.25  ,  0.0625]])

In [152]:
#hidden tests for problem 2.5 are within this cell

<strong>2.6</strong> \[1 pt\] If $AD=I$, where $A$ is as in Problem 2.2 and $I$ is the identity matrix, what is matrix D? Please store matrix D into a variable <strong>D</strong>.  (Use A from problem 2.2).

For grading purposes, `D` should be type `numpy.ndarray`.

In [153]:
A = ([-2,6,8],[5,-2,8],[2,1,4])
D = inv(A)
D
#raise NotImplementedError()

array([[-0.2   , -0.2   ,  0.8   ],
       [-0.05  , -0.3   ,  0.7   ],
       [ 0.1125,  0.175 , -0.325 ]])

In [154]:
assert type(D) == np.ndarray,  "Problem 2.6, testing D, type of value stored in variable does not match the expected type. Expecting np.array"

<strong>2.7</strong> \[1 pt\] What is the determinant of A? Please store the value into a variable <strong>A_deter</strong>.  (Use A from problem 2.2.) 

For grading purposes, `A_deter` should be type `numpy.float64`.

In [155]:
A = np.array([[-2,6,8],[5,-2,8],[2,1,4]])

A_deter=np.linalg.det(A)
A_deter
# YOUR CODE HERE
#raise NotImplementedError()

79.99999999999997

In [156]:
#hidden tests for problem 2.7 are within this cell

<strong>2.8</strong> \[1 pt\] What is the determinant of BA? Please store the value into a variable <strong>BA_deter</strong>.  (Use A and B from problem 2.2.)

For grading purposes, `BA_deter` should be type `numpy.float64`.

In [157]:
A = np.array([[-2,6,8],[5,-2,8],[2,1,4]])
B = np.array([[10,-4,6],[1,8,-3],[8,-2,4]])
BA_deter=np.linalg.det(np.dot(B,A))
BA_deter
# YOUR CODE HERE
#raise NotImplementedError()

-1920.0000000000377

In [158]:
#hidden tests for problem 2.8 are within this cell

<strong>2.9</strong> \[1 pt\] Change negative values of A to 1 and store the result into a variable <strong>A_pos</strong>.   (Use A from problem 2.2.)  Hint:  boolean matrix 

For grading purposes, `A` should be type `numpy.matrix`.

In [159]:
A = np.matrix([[-2,6,8],[5,-2,8],[2,1,4]])
A[A < 0] = 1
A_pos = A
A_pos
# YOUR CODE HERE
#raise NotImplementedError()

matrix([[1, 6, 8],
        [5, 1, 8],
        [2, 1, 4]])

In [160]:
#hidden tests for problem 2.9 are within this cell

<strong>2.10</strong> \[1 pt\] We are going to find the trace of the sum of two scaled matrices. Find the trace of 2\*A + 3\*B and store the value into a variable <strong>trace2A3B</strong>.  (Use A and B from problem 2.2.)

For grading purposes, `trace2A3B` should be type `numpy.int64`.

In [161]:
A = np.array([[-2,6,8],[5,-2,8],[2,1,4]])
B = np.array([[10,-4,6],[1,8,-3],[8,-2,4]])
C = (2*A) + (3*B)
trace2A3B=np.trace(C)
trace2A3B


# YOUR CODE HERE
#raise NotImplementedError()

66

In [162]:
#hidden tests for problem 2.10 are within this cell

<strong>2.11</strong> \[1 pt\] What is the value of tr(AB<sup>T </sup>)? Please store the value into a variable <strong>AB_trace</strong>.  (Use A and B from problem 2.2).

For grading purposes, `AB_trace` should be type `numpy.int64`.

In [163]:
ABtrans = np.dot(A, np.transpose(B))
AB_trace = np.trace(ABtrans)


# YOUR CODE HERE
#raise NotImplementedError()

In [164]:
assert type(AB_trace) == np.int64, "Problem 2.11, testing AB_trace, type of value stored in variable does not match the expected type. Expecting np.int64"

## Part 3: Matrix Calculations 

<strong>3.1</strong> \[1 pt\] Let $F = [[1, 2, a], [3, 2, 1 + b], [2, 2, 2 + c]]$ where $a$, $b$, and $c$ are variables.  $G = [[0, 2 + c, -a], [3, b + c, -1], [a, 3, -b]]$ where $a$, $b$, and $c$ are the same variables as in $F$.   What is the value of $F + G$? Please store the value into a string <strong>FG_sum</strong> written with valid python code formatting (e.g. FG_sum = "[[1, 2, a], [3, 2, 1 + b], [2, 2, 2 + c]]").  (Note you are encouraged to do this by hand.)

In [165]:
FG_sum = "[[1, 4 + c, 0],[6, 2 + b + c, b], [2 + a, 5, 2 + c - b]]"
# YOUR CODE HERE
#raise NotImplementedError()

In [166]:
assert type(FG_sum) == str, "Problem 3.1, type of value stored in variable FG_summ does not match the expected type."

<strong>3.2</strong> \[1 pt\] Assume F and G as above.  What is the (matrix) product of F and G? Please store your answers into a string variable <strong>Prod_FG</strong>  written with valid python code formatting (e.g. FG_sum = "[[1, 2, a], [3, 2, 1 + b], [2, 2, 2 + c]]"). (Note you are encouraged to do this by hand.)


In [167]:
Prod_FG = "[[6 + a ** 2, (2 + c) + (2 * (b + c)) + (a * 3), (1 * -a) + (2 * -1) + (a * -b)], [6 + (a * (1 + b)), (3 * (2 + c)) + (2 * (b + c)) + (3 * (1 + b)), (3 * -a) + (2 * -1) + (-b * (1 + b))], [6 + (a * (2 + c)), (2 * (2 + c)) + (2 * (b + c)) + (3 * (2 + c)), (2 * -a) + (2 * -1) + (-b * (2 + c))]]"

# YOUR CODE HERE
#raise NotImplementedError()

In [168]:
assert type(Prod_FG) == str, "Problem 3.2, type of value stored in variable Prod_FG does not match the expected type."

<strong>3.3</strong> \[1 pt\] What is the transpose of F?  Please store your answers into a string variable <strong>F_trans</strong>  written with valid python code formatting (e.g. F_trans = "[[1, 2, a], [3, 2, 1 + b], [2, 2, 2 + c]]"). (Note you are encouraged to do this by hand.)

In [169]:
F_trans = "[[1, 3, 2], [2, 2, 2], [a, 1 + b, 2 + c]]"
# YOUR CODE HERE
#raise NotImplementedError()

In [170]:
assert type(F_trans) == str, "Problem 3.3, type of value stored in variable F_trans does not match the expected type."

 <strong>3.4</strong> \[1 pt\] What is the determinant of F? Please store your answers into a string variable <strong>Det_F</strong>  written with valid python code formatting (e.g. F_trans = "2 + a -b"). (Note you are encouraged to do this by hand.)

In [171]:
 Det_F = "(1 * ((2 * (2 + c)) - (2 * (1 + b)))) - (2 * ((3 * (2 + c)) - (2 * (1 + b)))) + (a * 2)"
# YOUR CODE HERE
#raise NotImplementedError()

In [172]:
assert type(Det_F) == str, "Problem 3.4, type of value stored in variable Det_F does not match the expected type."

<strong>3.5</strong> \[1 pt\] What is the trace of the matrix 3F + 2G?    Please store your answers into a string variable <strong>Trace_FG</strong>  written with valid python code formatting (e.g. Trace_FG = "2 + a -b"). (Note you are encouraged to do this by hand.)


In [173]:
import numpy as np

Trace_FG = "3 + (6 + (2 * (b + c))) + ((3 * (2 + c)) + (2 * -b))"
Trace_FG
# YOUR CODE HERE
#raise NotImplementedError()

'3 + (6 + (2 * (b + c))) + ((3 * (2 + c)) + (2 * -b))'

In [174]:
assert type(Trace_FG) == str, "Problem 3.5, type of value stored in variable Trace_FG does not match the expected type."

<strong>3.6</strong> \[1 pt\] What is the trace of the matrix $F^T \cdot  G^T$?    Please store your answers into a string variable <strong>Trace_FTGT</strong>  written with valid python code formatting (e.g. Trace_FTGT = "2 + a -b"). (Note you are encouraged to do this by hand.)

Hint: no/very little additional calculation is necessary! 


In [175]:
Trace_FTGT= "(6 + a ** 2) + ((3 * (2 + c)) + (2 * (b + c)) + (3 * (1 + b))) + ((2 * -a) + (2 * -1) + (-b * (2 + c)))"
# YOUR CODE HERE
#raise NotImplementedError()


In [176]:
assert type(Trace_FTGT) == str, "Problem 3.6, type of value stored in variable Trace_FTGT does not match the expected type."

# Part 4: Image 

OpenCV is an open source computer vision library(https://opencv-python-tutroals.readthedocs.io/en/latest/py_tutorials/py_setup/py_intro/py_intro.html#intro). It is used in deep learning or image processing. Here, we will import cv2 and then use it to read the Michigan_logo and plot the image. If you are unfamilair with the library, you may need to read some of the documentation.




In [177]:
pip install opencv-python

Note: you may need to restart the kernel to use updated packages.


In [254]:
import cv2
from matplotlib import pyplot as plt
from scipy import ndimage


<strong>4.1</strong> Please use pyplot to read the image and plot the image below. 

In [179]:


#filesource = mpimg.imread('assets/Michigan_logo.jpg')
img = mpimg.imread('assets/Michigan_logo.jpg')
imgplot = plt.imshow(img)

img = plt.imshow(img)
plt.show()
# YOUR CODE HERE
#raise NotImplementedError()

NameError: name 'mpimg' is not defined

<strong>4.2</strong> \[1 pt\] What are the RGB values of the pixel at 10, 15 within the image? Please store your answer in a string format: <strong>ANS42</strong> = "R:, G:, B:". (example, string may look like the following “R:13, G:2, B:100”.) (Hint: use the python format function)

In [180]:
#ANS42= ""
# YOUR CODE HERE
#raise NotImplementedError()
#print(ANS42)


img1 = mpimg.imread('assets/Michigan_logo.jpg')
RGB = img1[10,15]
ANS42= "R:{}, G:{}, B:{}".format(RGB[0], RGB[1], RGB[2])
ANS42
print(ANS42)

NameError: name 'mpimg' is not defined

In [181]:
#hidden tests for problem 4.2 are within this cell

<strong>4.3</strong> Please resize the image to 20x20 using cv2.

In [182]:

# YOUR CODE HERE
raise NotImplementedError()

NotImplementedError: 

<strong>4.4</strong> \[1 pt\] What is the dimension of the image? Please store the result into the variable <strong>resized_dim</strong>. 

In [ ]:
resized_dim = None
# YOUR CODE HERE
raise NotImplementedError()

In [ ]:
#hidden tests for problem 4.4 are within this cell